# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: MyOwn

variables:
  buildConfiguration: 'Release'
  Pipeline.Workspace: '1/s/bin/Release/net10.0/WebSample.dll'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'
  testResultsDir: '$(Agent.TempDirectory)/TestResults'

steps:
- checkout: self
  fetchDepth: 0

- task: SonarCloudPrepare@4
  inputs:
    SonarQube: 'MySonarCloud'
    organization: 'xgg0111'
    scannerMode: 'dotnet'
    projectKey: 'xgg0111_test1'
    projectName: 'test1'



- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

- script: dotnet --info
  displayName: 'dotnet --info'

- script: dotnet restore WebSample
  displayName: 'Restore'

- script: dotnet build WebSample -c $(buildConfiguration) --no-restore
  displayName: 'Build'

# run Sonar analysis
- task: SonarCloudAnalyze@4
  inputs:
    jdkversion: 'JAVA_HOME'



- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/mypublish'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'WebSample.dll'
    publishLocation: 'pipeline'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'WebSample.Tests/WebSample.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" --logger trx'
#    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./MyCoverage/'
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
    pathToSources: 'WebSample'
#    codeCoverageTool: 'Cobertura'
    failIfCoverageEmpty: true

#- task: WhiteSource@21
#  inputs:
#    cwd: '$(System.DefaultWorkingDirectory)'
#    projectName: 'Internal1'