# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: MyOwn

variables:
  buildConfiguration: 'Release'
  Pipeline.Workspace: '1/s/bin/Release/net10.0/WebSample.dll'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'


steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

- script: dotnet --info
  displayName: 'dotnet --info'

- script: dotnet restore
  displayName: 'Restore'

- script: dotnet build -c $(buildConfiguration) --no-restore
  displayName: 'Build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/mypublish'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'WebSample.dll'
    publishLocation: 'pipeline'

- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'Internal1'